__title__ = "Subneteo VLSM"
__version__ = "0.0.3"
__author__ = "Angel Rodriguez"
__email__ = "venegasrv@outlook.com"
__description__ = "Paquete para operar redes y subredes"
__url__ = "https://github.com/AngelRodriguezV/Subneteo_VLSM_proyecto_Python"
__license__ = "MIT License"